/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArtifactsRouteImport } from './routes/artifacts'
import { Route as ChaptersRouteImport } from './routes/chapters'
import { Route as CharactersRouteImport } from './routes/characters'
import { Route as ThemesRouteImport } from './routes/themes'
import { Route as ChaptersIndexRouteImport } from './routes/chapters.index'
import { Route as ChaptersRangeIdRouteImport } from './routes/chapters.$rangeId'
import { Route as CharactersIndexRouteImport } from './routes/characters.index'
import { Route as CharactersSlugRouteImport } from './routes/characters.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtifactsRoute = ArtifactsRouteImport.update({
  id: '/artifacts',
  path: '/artifacts',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersRoute = ChaptersRouteImport.update({
  id: '/chapters',
  path: '/chapters',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersRoute = CharactersRouteImport.update({
  id: '/characters',
  path: '/characters',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemesRoute = ThemesRouteImport.update({
  id: '/themes',
  path: '/themes',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersIndexRoute = ChaptersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChaptersRoute,
} as any)
const ChaptersRangeIdRoute = ChaptersRangeIdRouteImport.update({
  id: '/$rangeId',
  path: '/$rangeId',
  getParentRoute: () => ChaptersRoute,
} as any)
const CharactersIndexRoute = CharactersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CharactersRoute,
} as any)
const CharactersSlugRoute = CharactersSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CharactersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artifacts': typeof ArtifactsRoute
  '/chapters': typeof ChaptersRouteWithChildren
  '/characters': typeof CharactersRouteWithChildren
  '/themes': typeof ThemesRoute
  '/chapters/$rangeId': typeof ChaptersRangeIdRoute
  '/characters/$slug': typeof CharactersSlugRoute
  '/chapters/': typeof ChaptersIndexRoute
  '/characters/': typeof CharactersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/artifacts': typeof ArtifactsRoute
  '/themes': typeof ThemesRoute
  '/chapters/$rangeId': typeof ChaptersRangeIdRoute
  '/characters/$slug': typeof CharactersSlugRoute
  '/chapters': typeof ChaptersIndexRoute
  '/characters': typeof CharactersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/artifacts': typeof ArtifactsRoute
  '/chapters': typeof ChaptersRouteWithChildren
  '/characters': typeof CharactersRouteWithChildren
  '/themes': typeof ThemesRoute
  '/chapters/$rangeId': typeof ChaptersRangeIdRoute
  '/characters/$slug': typeof CharactersSlugRoute
  '/chapters/': typeof ChaptersIndexRoute
  '/characters/': typeof CharactersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/artifacts'
    | '/chapters'
    | '/characters'
    | '/themes'
    | '/chapters/$rangeId'
    | '/characters/$slug'
    | '/chapters/'
    | '/characters/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/artifacts'
    | '/themes'
    | '/chapters/$rangeId'
    | '/characters/$slug'
    | '/chapters'
    | '/characters'
  id:
    | '__root__'
    | '/'
    | '/artifacts'
    | '/chapters'
    | '/characters'
    | '/themes'
    | '/chapters/$rangeId'
    | '/characters/$slug'
    | '/chapters/'
    | '/characters/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtifactsRoute: typeof ArtifactsRoute
  ChaptersRoute: typeof ChaptersRouteWithChildren
  CharactersRoute: typeof CharactersRouteWithChildren
  ThemesRoute: typeof ThemesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artifacts': {
      id: '/artifacts'
      path: '/artifacts'
      fullPath: '/artifacts'
      preLoaderRoute: typeof ArtifactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters': {
      id: '/chapters'
      path: '/chapters'
      fullPath: '/chapters'
      preLoaderRoute: typeof ChaptersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters': {
      id: '/characters'
      path: '/characters'
      fullPath: '/characters'
      preLoaderRoute: typeof CharactersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/themes': {
      id: '/themes'
      path: '/themes'
      fullPath: '/themes'
      preLoaderRoute: typeof ThemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/': {
      id: '/chapters/'
      path: '/'
      fullPath: '/chapters/'
      preLoaderRoute: typeof ChaptersIndexRouteImport
      parentRoute: typeof ChaptersRoute
    }
    '/chapters/$rangeId': {
      id: '/chapters/$rangeId'
      path: '/$rangeId'
      fullPath: '/chapters/$rangeId'
      preLoaderRoute: typeof ChaptersRangeIdRouteImport
      parentRoute: typeof ChaptersRoute
    }
    '/characters/': {
      id: '/characters/'
      path: '/'
      fullPath: '/characters/'
      preLoaderRoute: typeof CharactersIndexRouteImport
      parentRoute: typeof CharactersRoute
    }
    '/characters/$slug': {
      id: '/characters/$slug'
      path: '/$slug'
      fullPath: '/characters/$slug'
      preLoaderRoute: typeof CharactersSlugRouteImport
      parentRoute: typeof CharactersRoute
    }
  }
}

interface ChaptersRouteChildren {
  ChaptersRangeIdRoute: typeof ChaptersRangeIdRoute
  ChaptersIndexRoute: typeof ChaptersIndexRoute
}

const ChaptersRouteChildren: ChaptersRouteChildren = {
  ChaptersRangeIdRoute: ChaptersRangeIdRoute,
  ChaptersIndexRoute: ChaptersIndexRoute,
}

const ChaptersRouteWithChildren = ChaptersRoute._addFileChildren(
  ChaptersRouteChildren,
)

interface CharactersRouteChildren {
  CharactersSlugRoute: typeof CharactersSlugRoute
  CharactersIndexRoute: typeof CharactersIndexRoute
}

const CharactersRouteChildren: CharactersRouteChildren = {
  CharactersSlugRoute: CharactersSlugRoute,
  CharactersIndexRoute: CharactersIndexRoute,
}

const CharactersRouteWithChildren = CharactersRoute._addFileChildren(
  CharactersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtifactsRoute: ArtifactsRoute,
  ChaptersRoute: ChaptersRouteWithChildren,
  CharactersRoute: CharactersRouteWithChildren,
  ThemesRoute: ThemesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
